name = "coopex-site"
main = "app.py"
compatibility_date = "2026-10-03"
compatibility_flags = ["python_workers"]

[[d1_databases]]
binding = "DB"
database_name = "coopex-site"
database_id = "85e33289-f9d6-4dea-8e96-5ab7ddafb04c"

[assets]
directory = "./static"
binding = "ASSETS"
run_worker_first = [
    "/",
    "/static/*",
    "/admin-coopex*",
    "/admin-site*",
    "/arquivo/*",
    "/api/*",
    "/trabalhe-conosco/*",
    "/politica-de-privacidade",
    "/instagram",
    "/card-instagram",
    "/card-link/*",
    "/parceiro/*"
]

[python_modules]
exclude = [
    "**/*.pyc",
    "**/__pycache__"
]
